apiVersion: apps/v1
kind: Deployment
metadata:
  name: marianne
  namespace: default 
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb 
    spec:
      containers:
      - image: mariadb:10.6.3-focal
        name: mariadb
        ports:
          - containerPort: 3306
            name: db-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-password