apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: git@github.com:dennts/gowebservice.git 
    path: apps
    targetRevision: HEAD

