apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.0-rc1/manifests/install.yaml
    targetRevision: HEAD
