apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebservice
  namespace: default
spec:
  project: gowebservice
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/dennts/gowebservice.git
    path: basicwebservice
    targetRevision: HEAD
