apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: basicwebservice
build:
  artifacts:
  - image: ghcr.io/dennislinden/gowebservice
    context: ../scripts
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ../git_webserverdeployment.yaml
    - ../scripts/webserver-app-deployment.yaml
