apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: basicwebservice
build:
  artifacts:
  - image: ghcr.io/dennislinden/gowebservice
    context: ../code
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ../git_webserverdeployment.yaml
    - ../code/webserver-app-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: appel
    port: 8080
    localPort: 8082