apiVersion: apps/v1
kind: Deployment
metadata:
  name: appel
  namespace: default 
spec:
  selector:
    matchLabels:
      app: gowebservice
  template:
    metadata:
      labels:
        app: gowebservice
    spec:
      containers:
      - image: ghcr.io/dennislinden/gowebservice:v0.1
        name: pieter
        user: dennislinden
        password: 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
  replicas: 1
