apiVersion: apps/v1
kind: Deployment
metadata:
  name: appel
  namespace: default 
spec:
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - image: ghcr.io/dennislinden/webservice:v0.1
        name: webservice_container
  replicas: 1
